export const SEARCH_DISH_SUCCESS = 'SEARCH_DISH_SUCCESS'; 
export const GET_RANDOM_DISHES_SUCCESS = 'GET_RANDOM_DISHES_SUCCESS';
export const GET_CERTAIN_DISH_SUCCESS = 'GET_CERTAIN_DISH_SUCCESS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_AREA_LIST = 'GET_AREA_LIST';
export const API_SEARCH_BY_AREA = 'API_SEARCH_BY_AREA';
export const API_SEARCH_BY_AREA_SUCCESS = 'API_SEARCH_BY_AREA_SUCCESS';
export const API_SEARCH_BY_CATEGORY_SUCCESS = 'API_SEARCH_BY_CATEGORY_SUCCESS';

export const API_STATUS_STARTED = 'API_STATUS_STARTED'; 
export const API_STATUS_FAILURE = 'API_STATUS_FAILURE';

