export const SEARCH_DISH_SUCCESS = 'SEARCH_DISH_SUCCESS'; 
export const GET_RANDOM_DISHES_SUCCESS = 'GET_RANDOM_DISHES_SUCCESS';
export const GET_CERTAIN_DISH_SUCCESS = 'GET_CERTAIN_DISH_SUCCESS';

export const API_STATUS_STARTED = 'API_STATUS_STARTED'; 
export const API_STATUS_FAILURE = 'API_STATUS_FAILURE';
